import { sql } from "drizzle-orm";
import { sqliteTable, integer, text, real, primaryKey } from "drizzle-orm/sqlite-core";
import { relations } from "drizzle-orm";
import autoprefixer from "autoprefixer";

/**
 * Authentication schema.
 *
 * Generated by better-auth CLI.
 *
 * Only make changes to these tables if you know what you're doing.
 */
export const user = sqliteTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: integer("email_verified", { mode: "boolean" })
    .default(false)
    .notNull(),
  image: text("image"),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const session = sqliteTable("session", {
  id: text("id").primaryKey(),
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
  token: text("token").notNull().unique(),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

export const account = sqliteTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: integer("access_token_expires_at", {
    mode: "timestamp_ms",
  }),
  refreshTokenExpiresAt: integer("refresh_token_expires_at", {
    mode: "timestamp_ms",
  }),
  scope: text("scope"),
  password: text("password"),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const verification = sqliteTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

/**
 * Below, feel free to delete/update/add tables as you see fit for your app.
 */


// --- CATEGORY TABLES ---

export const foodCat = sqliteTable("FOOD_CAT", {
  id: integer("id").primaryKey({autoIncrement: true}),
  name: text("name").notNull(),
});

export const recipeCat = sqliteTable("RECIPE_CAT", {
  id: integer("id").primaryKey({autoIncrement: true}),
  name: text("name").notNull().unique(),
});

export const ingredientCat = sqliteTable("INGREDIENT_CAT", {
  id: integer("id").primaryKey({ autoIncrement: true}),
  name: text("name").notNull(),
});

export const unit = sqliteTable("UNIT", {
  id: integer("id").primaryKey({autoIncrement: true}), //// evtl shortForm als PK
  name: text("name").notNull(),
  shortForm: text("short_form"),
});

/*INSERT OR IGNORE INTO "UNIT" ("name","short_form") VALUES
 ('Gramm','g'),
 ('Kilogramm','kg'),
 ('Milliliter','ml'),
 ('Liter','l'),
 ('Teelöffel','TL'),
 ('Esslöffel','EL'),
 ('Stück','stk');
*/

// --- MAIN TABLES ---

export const recipe = sqliteTable("RECIPE", {
  id: integer("id").primaryKey({ autoIncrement: true}),
  title: text("title").notNull(),
  prepareTime: integer("prepare_time").notNull(),
  cookingTime: integer("cooking_time").notNull(),
  portions: integer("portions").notNull(),
  foodCategory: integer("food_category").references(() => foodCat.id).notNull(),
});

export const ingredients = sqliteTable("INGREDIENTS", {
  id: integer("id").primaryKey( {autoIncrement: true}),
  name: text("name").notNull(),
  category: integer("category").references(() => ingredientCat.id),
  unit: integer("unit").references(() => unit.id),
});

// --- RELATION TABLES ---

export const recipeIngredients = sqliteTable(
  "RECIPE_INGREDIENTS",
  {
    recipeId: integer("recipe_id").references(() => recipe.id),
    ingredientId: integer("ingredient_id").references(() => ingredients.id),
    amount: integer("amount").notNull(),
  },
  (table) => ({
    pk: primaryKey({ columns: [table.recipeId, table.ingredientId] }),
  }),
);

export const recipeAttributes = sqliteTable(
  "RECIPE_ATTRIBUTES",
  {
    recipeId: integer("recipe_id").references(() => recipe.id),
    recipeCat: integer("recipe_cat").references(() => recipeCat.id),
  },
  (table) => ({
    pk: primaryKey({ columns: [table.recipeId, table.recipeCat] }),
  }),
);

// --- STEP TABLE ---

export const recipeSteps = sqliteTable("RECIPE_STEPS", {
  id: integer("id").primaryKey({ autoIncrement: true}),
  recipeId: integer("recipe_id").references(() => recipe.id).notNull(),
  stepNumber: integer("step_number").notNull(),
  step: text("step").notNull(),
});

// --- SHOPPING LIST TABLE ---

export const shoppingList = sqliteTable("SHOPPING_LIST", {
  id: integer("id").primaryKey({ autoIncrement: true}),
  ingredientId: integer("ingredient_id").references(() => ingredients.id),
  dateOfUse: real("date_of_use"),
  amount: integer("amount"),
  unitId: integer("unitId").references(() => unit.id),
  checked: integer("checked", { mode: "boolean" }),
});

// --- CALENDAR TABLE ---

export const calendar = sqliteTable(
  "CALENDAR",
  {
    date: real("date"),
    daytime: real("daytime").references(() => foodCat.id), // based on diagram
    recipe_id: integer("recipe").references(() => recipe.id),
  },
  (table) => ({
    pk: primaryKey({ columns: [table.date, table.daytime] }),
  }),
);

// --- RELATIONS (optional, for Drizzle ORM) ---

export const recipeRelations = relations(recipe, ({ many, one }) => ({
  steps: many(recipeSteps),
  ingredients: many(recipeIngredients),
  attributes: many(recipeAttributes),
  category: one(foodCat, {
    fields: [recipe.foodCategory],
    references: [foodCat.id],
  }),
}));

export const ingredientRelations = relations(ingredients, ({ one, many }) => ({
  category: one(ingredientCat, {
    fields: [ingredients.category],
    references: [ingredientCat.id],
  }),
  unit: one(unit, {
    fields: [ingredients.unit],
    references: [unit.id],
  }),
  recipeLinks: many(recipeIngredients),
}));
