import { sql } from "drizzle-orm";
import { sqliteTable, text, integer, primaryKey } from "drizzle-orm/sqlite-core";

/**
 * Authentication schema.
 *
 * Generated by better-auth CLI.
 *
 * Only make changes to these tables if you know what you're doing.
 */
export const user = sqliteTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: integer("email_verified", { mode: "boolean" })
    .default(false)
    .notNull(),
  image: text("image"),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const session = sqliteTable("session", {
  id: text("id").primaryKey(),
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
  token: text("token").notNull().unique(),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

export const account = sqliteTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: integer("access_token_expires_at", {
    mode: "timestamp_ms",
  }),
  refreshTokenExpiresAt: integer("refresh_token_expires_at", {
    mode: "timestamp_ms",
  }),
  scope: text("scope"),
  password: text("password"),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const verification = sqliteTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

/**
 * Below, feel free to delete/update/add tables as you see fit for your app.
 */

// ---------------------------------------------------------
// FOOD / CATEGORY / UNIT
// ---------------------------------------------------------

export const foodCat = sqliteTable("food_cat", {
  id: integer("id").primaryKey(),
  name: text("name").notNull(),
});

export const recipeCat = sqliteTable("recipe_cat", {
  id: integer("id").primaryKey(),
  name: text("name").notNull(),
});

export const ingredientCat = sqliteTable("ingredient_cat", {
  id: integer("id").primaryKey(),
  name: text("name").notNull(),
});

export const unit = sqliteTable("unit", {
  id: integer("id").primaryKey(),
  name: text("name").notNull(),
  shortForm: text("short_form").notNull(),
});

// ---------------------------------------------------------
// INGREDIENTS
// ---------------------------------------------------------

export const ingredients = sqliteTable("ingredients", {
  id: integer("id").primaryKey(),
  name: text("name").notNull(),
  category: integer("category")
    .notNull()
    .references(() => ingredientCat.id, { onDelete: "restrict", onUpdate: "cascade" }),
  unit: integer("unit")
    .notNull()
    .references(() => unit.id, { onDelete: "restrict", onUpdate: "cascade" }),
});

// ---------------------------------------------------------
// RECIPE
// ---------------------------------------------------------

export const recipe = sqliteTable("recipe", {
  id: integer("id").primaryKey(),
  title: text("title").notNull(),
  steps: text("steps").notNull(),
  prepareTime: integer("prepare_time").notNull(),
  cookingTime: integer("cooking_time").notNull(),
  portions: integer("portions").notNull(),
  foodCategory: integer("food_category")
    .notNull()
    .references(() => foodCat.id, { onDelete: "restrict", onUpdate: "cascade" }),
});

// ---------------------------------------------------------
// RECIPE_INGREDIENTS
// ---------------------------------------------------------

export const recipeIngredients = sqliteTable(
  "recipe_ingredients",
  {
    recipeId: integer("recipe_id")
      .notNull()
      .references(() => recipe.id, { onDelete: "cascade", onUpdate: "cascade" }),
    ingredientId: integer("ingredient_id")
      .notNull()
      .references(() => ingredients.id, { onDelete: "restrict", onUpdate: "cascade" }),
    amount: integer("amount").notNull(),
  },
  (table) => ({
    pk: primaryKey({ columns: [table.recipeId, table.ingredientId] }),
  }),
);

// ---------------------------------------------------------
// RECIPE_ATTRIBUTES
// ---------------------------------------------------------

export const recipeAttributes = sqliteTable(
  "recipe_attributes",
  {
    recipeId: integer("recipe_id")
      .notNull()
      .references(() => recipe.id, { onDelete: "cascade", onUpdate: "cascade" }),
    recipeCat: integer("recipe_cat")
      .notNull()
      .references(() => recipeCat.id, { onDelete: "restrict", onUpdate: "cascade" }),
  },
  (table) => ({
    pk: primaryKey({ columns: [table.recipeId, table.recipeCat] }),
  }),
);

// ---------------------------------------------------------
// SHOPPING_LIST
// ---------------------------------------------------------

export const shoppingList = sqliteTable("shopping_list", {
  id: integer("id").primaryKey(),
  ingredientId: integer("ingredient_id")
    .notNull()
    .references(() => ingredients.id, { onDelete: "cascade", onUpdate: "cascade" }),
  dateOfUse: text("date_of_use").notNull(),
  amount: integer("amount").notNull(),
  checked: integer("checked", { mode: "boolean" }).default(false).notNull(),
});

// ---------------------------------------------------------
// CALENDAR
// ---------------------------------------------------------

export const calendar = sqliteTable(
  "calendar",
  {
    date: text("date").notNull(),
    daytime: integer("daytime")
      .notNull()
      .references(() => foodCat.id, { onDelete: "restrict", onUpdate: "cascade" }), // laut ERD
    recipe: integer("recipe")
      .notNull()
      .references(() => recipe.id, { onDelete: "cascade", onUpdate: "cascade" }),
  },
  (table) => ({
    pk: primaryKey({ columns: [table.date, table.daytime] }),
  }),
);
